### PR TITLE
Reset DialogInitialization state when decoupled submission is still pending on login

### LINKED ISSUE #439: Decoupled authentication is no longer possible because of error “Cannot init another dialog”
I'm using the code from the sample file login.php to access a bank account. Nothing is modified except bank and authentication data, which both are valid.

90 days ago this used to work without issue, however after trying to reauthenticate with a decoupled tan confirmation in the app, the second time `checkDecoupledSubmission` is executed, it fails: 

https://github.com/nemiah/phpFinTS/blob/master/Samples/login.php#L165
```
Fatal error: Uncaught RuntimeException: Cannot init another dialog. ./lib/Fhp/FinTs.php:429
Stack trace:
#0 ./Samples/login.php(165): Fhp\FinTs->checkDecoupledSubmission(Object(Fhp\Protocol\DialogInitialization))
#1 ./Samples/login.php(45): handleDecoupled(Object(Fhp\Protocol\DialogInitialization))
#2 ./Samples/login.php(195): handleStrongAuthentication(Object(Fhp\Protocol\DialogInitialization))
#3 {main}
  thrown in ./lib/Fhp/FinTs.php on line 429
```

How can I fix this?

### PR DESCRIPTION
**Pull request by Philipp91**
Fixes #439, maybe. If it doesn't fix it, let's discard this pull request.

### CODE REVIEW

**Comment by M-arcus** [comment]
@Philipp91 
Thank you for the code! :+1: 
Please merge this and release it as a new version, if possible. Then I can include it into our product.

**Comment by Philipp91** [comment]
Please test it first.

**Comment by M-arcus** [comment]
I have tested it, the second and all following requests work, also see my answer in https://github.com/nemiah/phpFinTS/issues/439#issuecomment-2194256033:
image

**Comment by M-arcus** [comment]
No, no, it's my fault, I put the positive result of the PR into the issue comment, not as comment in this PR, where it should have been.

**Pull request merged**
