### PR TITLE
Fix getTanModes if allowed tan mode not in all tan modes

### PR DESCRIPTION
**Pull request by roben**
After finally receiving a https url for Commerzbank this was a final fix to get it working.

### CODE REVIEW

**Comment by nemiah** [comment]
Any comments on this one? @ampaze @Philipp91

**Comment by Philipp91** [comment]
Could you please provide the concrete BPD and `allowedTanModes` that you received from the bank? Even if it's not fixable otherwise and we need to merge this patch, it's good to document here (and perhaps also in the commit message) _why_ we did that, in case someone stumbles upon this in the future. It's an oddness that requires some justification for future programmers not to simply remove it again.

**Comment by roben** [comment]
Sorry for the late reply. Getting this data would be rather complicated because I'd have to ask a customer for access to his system and then mess around with his actual bank account.

Maybe the relevant part of our error report suffices to document it:

```Error:
Error: Undefined array key 999

Backtrace:
[...]
library/Fhp/FinTs.php => error_function:534
?? => Fhp\{closure}:??
library/Fhp/FinTs.php => array_map:535
library/PicoErp/Hbci/Client.php => getTanModes:94
[...]```

As you can see, just calling `getTanModes()` leads to a PHP error.

**Comment by Philipp91** [comment]
`999` is a [special value](https://github.com/nemiah/phpFinTS/blob/3cf73b3afbdd2f22a3cce4bde574567c9fc40ee7/lib/Fhp/Model/TanMode.php#L19). I believe you want to use `NoPsd2TanMode` as shown in the README.

**Comment by roben** [comment]
I am not sure, because the customer was properly challenged with an image based TAN afterwards. According to the README, this tan mode is only needed for ING (which we already process this way).

Anyways, calling `getTanModes()` should not lead to a PHP error (as in error, not an Exception) because the bank did not return sane data. That's what this MR is for.

**Comment by Philipp91** [comment]
Ok fair enough.

**Comment by Philipp91** [comment]
Ah I guess the bank adds `999` to the list of TAN modes it supports. So an alternative implementation would be `if ($tanModeId === TanMode::SINGLE_STEP_ID) continue;`. What do you think? It would be more focused and more defensive coding, i.e. it would still allow us to discover different weird situation that warrant investigation. (In my experience, it's always better to surface errors than to swallow them.)

**Comment by roben** [comment]
That should be fine. We don't know if they also send something else, though, but that will be clear when this change is implemented.
Sorry for the long delays between my replies here, I have a rather large backlog currently.

**Comment by DerSpezialist** [comment]
Hey there,
is there a time frame when this fix will be implemented?
I'm trying to get my bank statements from Commerzbank, but i'm currently running in to this issue.

Thanks in advance!

**Comment by nemiah** [comment]
Are we fine with this one?

**Comment by Philipp91** [comment]
Yes

**Pull request merged**
