### PR TITLE
Fix: Response is not able to parse binary segment elements

### PR DESCRIPTION
**Pull request by fbett**
Response::findSegments and similar methods marked as deprecated:
They are not able to parse segment elements correctly, if there is a binary segment element.

### CODE REVIEW

**Comment by nemiah** [comment]
Thank you for your PR!
This are too many changes though, I can't check them.
Please send small PRs :blush:

**Comment by fbett** [comment]
Hi @nemiah, you are right.
It was also a big problem.

@Philipp91 could you help?

**Comment by Philipp91** [comment]
This conflicts with my plan to build a fresh `FinTs` class (currently called `FinTsNew`, hopefully uploaded soon) and get rid of the messier parts of the old code. It "conflicts" because it puts logic specific to the old code into the new `Parser` class (and already marks it as `@deprecated`). While I don't mind those classes being _used_ from the old `FinTs` or `Response` classes, I would prefer if they could remain untouched.

If you want to move forward with this for now (as I can't guarantee when the alternative design is ready), please move `parseRawSegments()` out (next) to its only call site, then I can rereview.

**Comment by nemiah** [comment]
Sorry, but I won't merge this PR.
It's too messy and I cannot tell what it all does :slightly_frowning_face:

**Comment by fbett** [comment]
Frustrating, that Github is not able to show commit changes by ignoring space/line endings (like git does it).
I hoped, my commit messages would explain what happened, but i see, they do not.
Hopefully we could solve this space/line endings problem soon, because my IDE (PHPStorm) automatically normalise often the full file, when i change only a few lines.

So, i explain my changes by the overall file changes.

**Summary:**
"Response" is not able to parse segments with binary data elements. More than that, "Response" and especially "Response::findSegments" handles each data element as a string.
The most problem about that: 
Within a binary data elements, delimiter will not be escaped. So there is always the risk, that the data elements are not detected correctly and splitted accidentally.
Another problem:
The splitted data elements are modified, by converting to a different character set(UTF8) or by handling XML payloads (f.e. in Response::findResponse()).
All these problems will destroy a binary payload.

In the past, someone has also detected this problem and had added an additional parameter "$fix = true" to Response::findSegments().

But this solves only some problems.

**Problem 1:**
The regex within Response:: unwrapEncryptedMsg() does not work, if a segment ends with a binary data element.
Probably because of that, someone has added a quick fix:
````
$rawResponse = preg_replace("/\@([0-9]*)\@HIRMG/", "@$1@'HIRMG", $rawResponse);
````
The problem with the quick fix is, that it generates two invalid formatted segments and will not be able to be parsed
**Solution 1:**
Response:: unwrapEncryptedMsg replaced and quick fix removed

**Problem 2:**
Response::findSegments() and similar methods modify data segments, ignore escaped delimiter and etc...

**Solution 2:**
Response should work only with correctly parsed segments. There is the "Parser", which is able to do that. Problem about that: each Response::findSegments() access has to be migrated manually (it's not done by simple search & replace) and I was not able to that in a small pull-request, so this is more a intermediate commit:
- Wrong working methods like "Response::findSegments()" marked as deprecated
- For compatibility reason a deprecated marked Response::$rawSegments introduced (Response::findSegments() will now use this array)
- New methods introduced like Response::getSegments() : Segment\BaseSegment|Segment\AbstractSegment|null
- Parser:: parseRawSegments() introduced and marked as deprecated to replace this faulty line:
````
$this->segments = preg_split("#'(?=[A-Z]{4,}:\d|')#", $rawResponse);
````
- To show how the Response::getSegment() method works, Response::getDialogId() migrated

These are all changes within the class "Response" :)

**Problem in class "Segment":**
Segment::createFromString ignores completely escaped delimiter and binary data elements.
So replaced all by using the existing and working Parser::detectAndParseSegment().

Don't worry about the big change in the return value: 
this method is currently not used

**Changes in class "Parser":**
- Parser::parseBinaryBlock(): Only some new lines for more readability
- Parser:: parseRawSegments(): New method introduced here and marked as deprecated, because it shares code from Parser::parseSegments()


**Epilog**
I do not insist, that the commit is merged as it is, especially if it conflicts with the solution from @Philipp91.
I can work with my fork until there is a new release. As @Philipp91 seems to work on this library offline the most time, i'm will not be able to help you there.

Beside of these changes, please don't forget to merge #126 someday. 
This is a really big fail! I searched an (non existing) error in my own code for about 1,5 days until i discovered this issue.

As told in #117 i committed my full work to get PhotoTan and serialised "GetTanRequest" objects in https://github.com/fbett/phpFinTS/commits/develop

Probably the most interesting commits are:
- New Segment: HITAN\HITANv6
- Response\GetTANRequest extended to get "Challenge" and "Challenge Image" (PhotoTan) (here you are able to see the benefit of using Segment objects in the Response class.)
- Response\GetTanRequest should be serialisable; Restorable DialogState introduced
- FinTS::finishSEPATANFromSerialized() introduced to use if a GetTanRequest is serialized

**Comment by nemiah** [comment]
Thank you for your explanations. I think I need to clarify:
I have no problem whatsoever with the changes of the PR, just with the amount of changes.
There are 13 commits. Some merges, some real changes. It's difficult for me to separate them and keep the overview. I see it as my job to make sure that I don't break (a lot of :grin:) things when merging any PR. Thus I ask you to please resubmit the PR with only the real changes :relaxed:

**Pull request closed without merging**
