### PR TITLE
adding composer.lock to git

### PR DESCRIPTION
**Pull request by lukas-staab**
Adding composer.lock to git repo, as discussed in #385 (https://github.com/nemiah/phpFinTS/pull/385#issuecomment-1213072667)

### CODE REVIEW

**Comment by nemiah** [comment]
Can the Travis error be fixed?

**Comment by lukas-staab** [comment]
yes, i wanted to wait until the other PR was done to rebase this one

**Comment by lukas-staab** [comment]
ah damn, it is more complex that I initially thought. The composer lock has locked down to php8.1 dependencies. Now the 8.1 check works, the other 2 are not. I see 2 possible solutions: run - in older php versions - a composer update in travis. We could also do it in the newer version - but then the composer.lock itself would be a bit meaningless. I tend to withdraw this PR and add a hint to the contribution guidelines instead, not only to run `composer cs-fix` but also `composer update` so local lock files do not get outdated. Any other opinions @nemiah @Philipp91 ?

**Comment by nemiah** [comment]
I usually opt for the simpler solution. Adding `composer update` to the Readme Contribute-section is fine by me :relaxed:

**Comment by lukas-staab** [comment]
fine by me as well. Then this PR can be closed imo

**Pull request closed without merging**
