### PR TITLE
Drop support for PHP7

### PR DESCRIPTION
**Pull request by Philipp91**
End of life was 28 Nov 2022.

### CODE REVIEW

**Comment by Philipp91** [comment]
@fbett FYI

I'm not yet dropping the `@deprecated Beginning from PHP7.4 __unserialize is used for new generated strings, then this method is only used for previously generated strings - remove after May 2023` things because it's not May yet.

**Comment by Philipp91** [comment]
This is a breaking change, so we need a new major release. I propose to bundle it with some cleanups that I'll send in more PRs, so people migrating to the new major release, who potentially do some more testing than with a minor release, also end up confirming that these cleanups don't break them.

**Comment by Philipp91** [comment]
Travis didn't run?

**Comment by nemiah** [comment]
I merged your previous PR, now git has an issue…

**Comment by Philipp91** [comment]
Fixing

**Comment by Philipp91** [comment]
Rebased

**Pull request merged**
